// @ts-check
import prettier from 'eslint-config-prettier'
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    // Generated by ts-rs from Rust, drift-checked in CI — not hand-formatted.
    ignores: ['src/types/bindings/**'],
  },
  // Disable core ESLint rules that would conflict with Prettier formatting.
  prettier,
)
