// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a bucket appears in the address: `https://host/<bucket>/<key>` or
 * `https://<bucket>.host/<key>`.
 */
export type Addressing = "path" | "virtual";
