// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdmissionDecideArgs = { 
/**
 * The key of the copy as hex.
 */
devicePubkey: string, 
/**
 * `true` admits the copy, `false` keeps it out.
 */
admit: boolean, };
