// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many entries and folders a trash command touched, folders counted with their content.
 */
export type AffectedResult = { affected: number, };
