// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentFileKind } from "./AgentFileKind";
import type { AgentFileStatus } from "./AgentFileStatus";

/**
 * One row.
 */
export type AgentFilePermission = { agentId: string, kind: AgentFileKind,
/**
 * Empty for the device, the storage id for a storage.
 */
target: string, status: AgentFileStatus, updatedAt: number, };
