// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The decision; `granted` for the device, `read` and `readWrite` for a storage.
 */
export type AgentFileStatus = "granted" | "read" | "readWrite" | "denied";
