// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentHeader } from "./AgentHeader";

export type AgentSearchResult = { items: Array<AgentHeader>, };
