// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the built-in agent may see of an entry (FR-027): title, tag names, folder name and whether
 * a TOTP exists. No username, no URL.
 */
export type AgentHeader = { id: string, title: string | null, tags: Array<string>, folder: string | null, hasTotp: boolean, };
