// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentSearchArgs = { query?: string, tag?: string,
/**
 * At most 50, 20 when left out.
 */
limit?: number, };
