// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttachmentSaveArgs = { attachmentId: string, 
/**
 * A path from the save dialog.
 */
path: string, };
