// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PickedFile } from "./PickedFile";

export type AttachmentSaveArgs = { attachmentId: string,
/**
 * The choice of the save dialog.
 */
file: PickedFile, };
