// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An attachment of an entry.
 */
export type AttachmentView = { id: string, fileName: string, size: number, binaryHash: string, };
