// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttentionKind } from "./AttentionKind";

/**
 * One place where the user has to rework by hand: entry, folder path and what is missing; never a
 * value of a secret.
 */
export type AttentionRow = { 
/**
 * The entry the place belongs to, so the window can open it; `None` for the source as a whole.
 */
itemId: string | null, title: string, folderPath: string, kind: AttentionKind, field: string | null, fileName: string | null, sizeMib: number | null, };
