// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an import could not bring over unchanged (contracts/import-mapping.md §Bericht).
 */
export type AttentionKind = "attachment_too_large" | "attachment_unreadable" | "passkey_key_unreadable" | "passkey_public_key_missing" | "passkey_duplicate" | "totp_invalid" | "icon_not_mapped" | "value_not_storable" | "source_setting";
