// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a bundle was refused: the error kind of the format (`archive_invalid`, `file_mismatch`, …,
 * contracts/bundle-format.md) and, for entry-level errors and `file_mismatch`, the path inside the
 * bundle.
 */
export type BundleRejection = { kind: string, path?: string, };
