// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Addressing } from "./Addressing";
import type { CredentialsInput } from "./CredentialsInput";
import type { ProviderKind } from "./ProviderKind";

/**
 * `storage_connection_save`: a new connection without `id`, otherwise a change of one.
 */
export type ConnectionInput = { id?: string, providerName: string, providerKind: ProviderKind, 
/**
 * Empty or absent only for `aws`.
 */
endpoint?: string, region: string, addressing: Addressing, 
/**
 * New credentials; required for a new connection.
 */
credentials?: CredentialsInput, 
/**
 * The bucket the test before saving uses (FR-003).
 */
bucketForTest: string, };
