// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Addressing } from "./Addressing";
import type { CredentialsState } from "./CredentialsState";
import type { EndpointOrigin } from "./EndpointOrigin";
import type { ProviderKind } from "./ProviderKind";

/**
 * A connection as the settings show it.
 */
export type ConnectionView = { id: string, providerName: string, providerKind: ProviderKind, endpoint: string, region: string, addressing: Addressing,
/**
 * The endpoint sends without encryption (`http`).
 */
insecure: boolean, endpointOrigin: EndpointOrigin, credentials: CredentialsState, };
