// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The title of a copy: the exact title for a single entry, or a suffix for several targets or a
 * folder (the window passes the localized default, " – Kopie" or " – Copy").
 */
export type CopyTitle = { "exact": string } | { "suffix": string };
