// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextField } from "./TextField";

export type CopyTextArgs = { text: string, 
/**
 * The entry the text belongs to, for its own placeholders; none for a new entry.
 */
itemId?: string, 
/**
 * The field the text comes from: its placeholders are resolved before the copy (FR-045).
 * Without it the text is copied as it is (a title, a date).
 */
field?: TextField, };
