// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which value `passwords_copy_field` puts on the clipboard.
 */
export type CopyField = { "kind": "username" } | { "kind": "password" } | { "kind": "totp" } | { "kind": "keyValue", id: string, } | { "kind": "url" } | { "kind": "note" };
