// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopyField } from "./CopyField";

export type CopyFieldArgs = { itemId: string, field: CopyField, };
