// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a copy made. No ids: the window reloads.
 */
export type CopyReport = { itemsCreated: number, groupsCreated: number, passkeyLinks: number,
/**
 * Targets that were deleted meanwhile (or lie in the trash) and were skipped.
 */
skippedMissing: number, };
