// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopyOptions } from "./CopyOptions";
import type { Target } from "./Target";

export type CopyArgs = { targets: Array<Target>, 
/**
 * `null` is the top level.
 */
intoGroupId: string | null, options: CopyOptions, };
