// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a copy did: after how many seconds the clipboard is cleared, `None` when that is off.
 */
export type CopyResult = { clearsInSeconds: number | null, };
