// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopyTitle } from "./CopyTitle";

export type CopyOptions = { title: CopyTitle, history: boolean, usernameAsReference: boolean, passwordAsReference: boolean, passkeysAsLinks?: boolean, };
