// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemInput } from "./ItemInput";

export type CreateItemArgs = { input: ItemInput, groupId?: string, };
