// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateGroupArgs = { name: string, description?: string, icon?: string, color?: string, parentId?: string, };
