// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the credentials entry of a connection is on this device (data-model.md): `syncing`
 * when it has not arrived yet, `missing` when the user deleted it.
 */
export type CredentialsState = "present" | "syncing" | "missing";
