// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Credentials as typed by the user; `Debug` shows only the access key id.
 */
export type CredentialsInput = { accessKeyId: string, secretAccessKey: string, sessionToken?: string | null, };
