// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One declared permission as the install dialog shows it.
 */
export type DeclaredPermissionView = { kind: string, action: string, target: string,
/**
 * Remembered only for this device (shell); every other kind holds on every own device.
 */
deviceScoped: boolean, };
