// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceDto } from "./WorkspaceDto";

export type DeleteWorkspaceResult = { workspaces: Array<WorkspaceDto>, activeWorkspaceId: string, };
