// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Target } from "./Target";

/**
 * What to delete for good; with `inline_references` the placeholders on the deleted entries are
 * first replaced by their values in the entries that hold them (spec 036, FR-048).
 */
export type DeletePermanentlyArgs = { targets: Array<Target>, inlineReferences?: boolean, };
