// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The state of an extension on one own device (US4, T080).
 */
export type DeviceState = { 
/**
 * The device's `vault_device_uuid`.
 */
deviceId: string, 
/**
 * The device's name; empty when it has none.
 */
deviceName: string, thisDevice: boolean, 
/**
 * `transferring`, `ready`, `signature_failed`, `migration_failed` or `disabled`.
 */
status: string, 
/**
 * The error kind (`migration_changed`, …), never data of the extension.
 */
error?: string, };
