// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What stops sync with a device (FR-029, FR-030).
 */
export type DeviceProblem = "incompatible_version" | "duplicate";
