// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Developer mode on this device and whether holzi's window can show development servers yet.
 */
export type DevModeState = { enabled: boolean,
/**
 * The document holzi's window shows was served with the development origins; when `enabled`
 * differs, the window reloads to take the new policy.
 */
framesAllowed: boolean, };
