// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The model a download would load.
 */
export type DownloadTarget = { "kind": "catalog", id: string, } | { "kind": "stt", id: string, } | { "kind": "file", sizeBytes: number | null, };
