// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the confirmation shows.
 */
export type DownloadCheck = {
/**
 * The size of the download; absent when no source names it.
 */
sizeBytes: number | null,
/**
 * The free space where models are stored; absent when the system does not tell.
 */
freeBytes: number | null,
/**
 * Whether the download fits with a reserve of a tenth of its size. Without a size or without
 * the free space there is nothing to warn about.
 */
fits: boolean, };
