// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A drive in the sidebar.
 */
export type Drive = { name: string, path: string, total: number | null, free: number | null, };
