// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Emptying the trash, with `inline_references` as for deleting for good.
 */
export type EmptyTrashArgs = { inlineReferences?: boolean, };
