// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who typed the endpoint (research R8): local addresses are only reached for the user's own.
 */
export type EndpointOrigin = "user" | "extension";
