// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The addresses an endpoint may reach (research R8, FR-009b), fixed when the endpoint is set:
 * `local` when its host resolves to loopback or private addresses, else `public`. Every call
 * checks each resolved address against it, so a public name that later points into the local
 * network (DNS rebinding) reaches nothing.
 */
export type EndpointScope = "public" | "local";
