// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";

/**
 * One entry of a folder (data-model.md).
 */
export type Entry = { name: string, 
/**
 * Device: the absolute path; storage: the key, folders ending in `/`.
 */
path: string, kind: EntryKind, 
/**
 * Files only.
 */
size: number | null, modifiedMs: number | null, mime: string | null, hidden: boolean, symlink: boolean, 
/**
 * The system denies access.
 */
noAccess: boolean, 
/**
 * In one of holzi's own places: read-only for the user (FR-037).
 */
holziOwned: boolean, };
