// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredPermissionView } from "./DeclaredPermissionView";

/**
 * The installed extension a bundle would update.
 */
export type ExistingInstall = {
/**
 * The effective version installed now.
 */
version: string,
/**
 * The bundle is older than the effective version; installing needs a confirmation.
 */
isDowngrade: boolean,
/**
 * Declarations without any remembered row yet; only these are put before the user.
 */
newPermissions: Array<DeclaredPermissionView>, };
