// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionChoice } from "./PermissionChoice";

export type ExtensionInstallArgs = { path: string, 
/**
 * The choice per declared permission; a declaration without a choice becomes `ask`.
 */
accepted: Array<PermissionChoice>, confirmDowngrade: boolean, };
