// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The limits of one extension (data-model.md `extension_limits`).
 */
export type ExtensionLimits = {
/**
 * Rows one query may return.
 */
maxRows: number,
/**
 * Requests running at the same time.
 */
maxConcurrent: number,
/**
 * Bytes of one SQL statement with its parameters.
 */
maxSqlBytes: number,
/**
 * Run time of one request in milliseconds.
 */
timeoutMs: number,
/**
 * Bytes of one answer.
 */
maxResponseBytes: number, };
