// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtensionStatusChanged = { extensionId: string, 
/**
 * `transferring`, `ready`, `signature_failed`, `migration_failed` or `disabled`.
 */
status: string, 
/**
 * The error kind, never data of the extension.
 */
error?: string, 
/**
 * The effective bundle of a running extension changed: open tabs reload.
 */
reload: boolean, };
