// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionChoice } from "./PermissionChoice";

export type ExtensionInstallArgs = { path: string,
/**
 * The choice per declared permission; a declaration without a choice becomes `ask`.
 */
accepted: Array<PermissionChoice>,
/**
 * The user confirmed a downgrade or the replacement of another bundle of the same version.
 */
confirmed: boolean, };
