// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One extension of the vault.
 */
export type ExtensionSummary = { id: string, name: string, 
/**
 * `displayName` of the effective bundle, else `name`.
 */
title: string, description?: string, 
/**
 * Version of the effective bundle; `None` while no bundle of it is live.
 */
version?: string, publisherFingerprint: string, enabled: boolean, 
/**
 * `installed`, or `removed` with its data kept (FR-008); one removed with its data is not
 * listed.
 */
state: string, 
/**
 * For `removed`: the bytes its kept tables take on this device, indexes included; `None` when
 * SQLite cannot tell.
 */
keptDataBytes?: number, 
/**
 * The app opens at most once (manifest `singleInstance`).
 */
singleInstance: boolean, hasIcon: boolean, 
/**
 * State on this device (`transferring`, `ready`, …); `None` before its first start here.
 */
statusHere?: string, 
/**
 * The error kind of that state.
 */
statusErrorHere?: string, 
/**
 * The state on every own device that started it, this device first. Inline, so the binding
 * imports nothing (the check scripts load it with Node's own module rules).
 */
devices: Array<{ 
/**
 * The device's `vault_device_uuid`.
 */
deviceId: string, 
/**
 * The device's name; empty when it has none.
 */
deviceName: string, thisDevice: boolean, 
/**
 * `transferring`, `ready`, `signature_failed`, `migration_failed` or `disabled`.
 */
status: string, 
/**
 * The error kind (`migration_changed`, …), never data of the extension.
 */
error?: string, }>, 
/**
 * A development version on this device (US12): enabled only while developer mode is on.
 */
dev: boolean, };
