// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The limits with the bounds the settings show next to them; the bounds are only checked here.
 */
export type ExtensionLimitsView = { values: { 
/**
 * Rows one query may return.
 */
maxRows: number, 
/**
 * Requests running at the same time.
 */
maxConcurrent: number, 
/**
 * Bytes of one SQL statement with its parameters.
 */
maxSqlBytes: number, 
/**
 * Run time of one request in milliseconds.
 */
timeoutMs: number, 
/**
 * Bytes of one answer.
 */
maxResponseBytes: number, }, min: { 
/**
 * Rows one query may return.
 */
maxRows: number, 
/**
 * Requests running at the same time.
 */
maxConcurrent: number, 
/**
 * Bytes of one SQL statement with its parameters.
 */
maxSqlBytes: number, 
/**
 * Run time of one request in milliseconds.
 */
timeoutMs: number, 
/**
 * Bytes of one answer.
 */
maxResponseBytes: number, }, max: { 
/**
 * Rows one query may return.
 */
maxRows: number, 
/**
 * Requests running at the same time.
 */
maxConcurrent: number, 
/**
 * Bytes of one SQL statement with its parameters.
 */
maxSqlBytes: number, 
/**
 * Run time of one request in milliseconds.
 */
timeoutMs: number, 
/**
 * Bytes of one answer.
 */
maxResponseBytes: number, }, };
