// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceRef } from "./SourceRef";

/**
 * Whether the agent may show the entry, and where the file browser opens.
 */
export type FilesAgentShow = { allowed: boolean,
/**
 * Why not: the code and message the agent gets.
 */
reason: string | null, source: SourceRef | null,
/**
 * The folder the browser opens.
 */
folder: string | null,
/**
 * The file opened in the viewer, by name in `folder`.
 */
open: string | null, };
