// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a filter looks for (spec 044 FR-029). The window mirrors [`category`] in
 * `src/lib/files/filters.ts`; `scripts/check-files-filters.ts` runs the same cases.
 */
export type FileCategory = "image" | "video" | "audio" | "document" | "text";
