// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kinds of [`FilesError`].
 */
export type FilesErrorCode = "invalidPath" | "invalidName" | "exists" | "intoItself" | "noSpace" | "holziOwned" | "noAccess" | "notFound" | "binary" | "broken" | "tooLarge" | "blocked" | "notGranted" | "unsupported" | "credentials" | "unreachable";
