// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilesErrorCode } from "./FilesErrorCode";

/**
 * Why a file operation was refused (contracts/tauri-commands.md). The message never holds
 * credentials or file contents (FR-033, FR-038).
 */
export type FilesError = { code: FilesErrorCode, message: string, };
