// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's answer.
 */
export type FilesAgentChoice = "read" | "readWrite" | "deny";
