// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the agent wants to do with the storage.
 */
export type FilesAgentWant = "read" | "readWrite";
