// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilesAgentWant } from "./FilesAgentWant";

/**
 * The payload of [`EVENT_PERMISSION_REQUEST`].
 */
export type FilesAgentPermissionRequest = { requestId: string, agentId: string, storageId: string, storageName: string, wants: FilesAgentWant, };
