// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchHit } from "./SearchHit";

/**
 * What the window hears of a search.
 */
export type FilesSearchEvent = { "kind": "hits", hits: Array<SearchHit>, } | { "kind": "progress", dirs: number, } | { "kind": "done", truncated: boolean, };
