// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A change in a watched folder; the window reloads it.
 */
export type FolderChanged = { paths: Array<string>, };
