// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FrameOpened = {
/**
 * Id of the frame session for bridge calls; never handed to the extension.
 */
frame: string,
/**
 * URL of the entry page with the start token, or of the development server.
 */
url: string,
/**
 * A development version (US12): its tab is marked, its console shown.
 */
dev: boolean, };
