// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupRow = { id: string, name: string | null, description: string | null, icon: string | null, color: string | null, sortOrder: number | null, parentId: string | null, trashedFromParentId: string | null, };
