// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A partial update of a folder: a field that is absent stays as it is, `null` clears it.
 */
export type GroupPatch = { name?: string | null, description?: string | null, icon?: string | null, color?: string | null, sortOrder?: number | null, };
