// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistorySecret } from "./HistorySecret";

export type HistoryRevealArgs = { snapshotId: string, field: HistorySecret, };
