// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which secret of a history state to reveal.
 */
export type HistorySecret = { "kind": "password" } | { "kind": "otpSecret" } | { "kind": "keyValue", key: string, };
