// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportSource } from "./ImportSource";
import type { OnDuplicate } from "./OnDuplicate";

export type ImportRunArgs = { source: ImportSource, path: string, password?: string, keyFilePath?: string, onDuplicate: OnDuplicate, };
