// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an import would bring over, counted before anything is written (FR-023). `warnings` are
 * the kinds of [`AttentionKind`] that occur, as their snake_case names; the window gives each a
 * text. Never a value of a secret.
 */
export type ImportPreview = { entries: number, groups: number, trashedEntries: number, historyStates: number, attachments: number, passkeys: number, duplicates: number, warnings: Array<string>, };
