// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttentionRow } from "./AttentionRow";

export type ImportReport = { imported: number, trashed: number, historyStates: number, skippedDuplicates: number, needsAttention: Array<AttentionRow>, };
