// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PickedFile } from "./PickedFile";

export type ImportInstanceArgs = {
/**
 * The choice of the open dialog.
 */
file: PickedFile, passphrase: string, };
