// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttentionRow } from "./AttentionRow";

export type ImportReport = { imported: number, trashed: number, historyStates: number, skippedDuplicates: number,
/**
 * KeePass references that became holzi placeholders (spec 036, FR-050).
 */
referencesConverted: number,
/**
 * KeePass references that stayed text (no unique source, or a field holzi cannot point at).
 */
referencesLeftAsText: number, needsAttention: Array<AttentionRow>, };
