// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportSource } from "./ImportSource";

export type ImportArgs = { source: ImportSource, path: string, password?: string, keyFilePath?: string, };
