// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The formats the import reads.
 */
export type ImportSource = "keepass" | "bitwarden" | "lastpass" | "haexvault";
