// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportSource } from "./ImportSource";
import type { PickedFile } from "./PickedFile";

export type ImportArgs = { source: ImportSource, file: PickedFile, password?: string, keyFile?: PickedFile, };
