// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundleRejection } from "./BundleRejection";
import type { DeclaredPermissionView } from "./DeclaredPermissionView";
import type { ExistingInstall } from "./ExistingInstall";

/**
 * What the install dialog shows before anything is written.
 */
export type InstallPreview = { 
/**
 * The bundle passed every check of the format.
 */
signatureValid: boolean, error?: BundleRejection, extensionId?: string, name?: string, displayName?: string, version?: string, description?: string, author?: string, 
/**
 * Short form of the publisher key: the first and last four groups of four hex digits.
 */
publisherFingerprint?: string, declared: Array<DeclaredPermissionView>, 
/**
 * Manifest categories holzi does not offer ("wird von holzi nicht unterstützt").
 */
unsupportedCategories: Array<string>, existing?: ExistingInstall, 
/**
 * A live bundle of the same version with other content is in the vault; installing replaces
 * it and needs a confirmation.
 */
replacesSameVersion: boolean, 
/**
 * Another installed extension has the same name but another publisher (US7-2).
 */
sameNameOtherPublisher: boolean, };
