// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceInfo = { 
/**
 * Basename without the `.db` extension.
 */
name: string, 
/**
 * Human-readable alias if set (from `known_devices`); `None` for
 * list results, filled later when needed.
 */
alias: string | null, 
/**
 * Milliseconds since UNIX epoch; sourced from the DB file's mtime.
 */
lastAccess: number, };
