// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagRef } from "./TagRef";

/**
 * The view of an entry without secrets that lists deliver (FR-026). No password, TOTP secret,
 * passkey key, custom field, note or attachment ever appears here; only whether they exist.
 */
export type ItemHeader = { id: string, title: string | null, username: string | null, url: string | null, icon: string | null, color: string | null,
/**
 * `trash`, a folder id or `None` for the root.
 */
groupId: string | null, tags: Array<TagRef>,
/**
 * `YYYY-MM-DD`.
 */
expiresAt: string | null, hasPassword: boolean, hasTotp: boolean, passkeyCount: number, attachmentCount: number, createdAt: string | null, updatedAt: string | null, };
