// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValueInput } from "./KeyValueInput";

/**
 * The data to create an entry with. Everything may be empty, also the title (FR-001).
 */
export type ItemInput = { title: string | null, username: string | null, password: string | null, note: string | null, url: string | null, icon: string | null, color: string | null, expiresAt: string | null,
/**
 * A secret or an `otpauth://` address; normalised and checked on create (FR-003).
 */
otpSecret: string | null, otpDigits: number | null, otpPeriod: number | null, otpAlgorithm: string | null, autofillAliases: string | null, tags: Array<string>, keyValues: Array<KeyValueInput>, };
