// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The names of the functions that use the entry; empty when none is registered.
 */
export type ItemUsageResult = { features: Array<string>, };
