// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValueInput } from "./KeyValueInput";

/**
 * The data to create an entry with. Everything may be empty, also the title (FR-001).
 */
export type ItemInput = { title?: string, username?: string, password?: string, note?: string, url?: string, icon?: string, color?: string, expiresAt?: string, 
/**
 * A secret or an `otpauth://` address; normalised and checked on create (FR-003).
 */
otpSecret?: string, otpDigits?: number, otpPeriod?: number, otpAlgorithm?: string, autofillAliases?: string, tags: Array<string>, keyValues: Array<KeyValueInput>, };
