// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A custom field to create.
 */
export type KeyValueInput = { key: string, value?: string, };
