// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A custom field in a partial update: `id` names an existing field, a missing `value` keeps its
 * stored value, a row with an empty key is dropped.
 */
export type KeyValuePatch = { id?: string, key: string, value?: string, };
