// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A custom field in the detail view: its name, never its value.
 */
export type KeyValueView = { id: string, key: string | null, hasValue: boolean, };
