// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefMark } from "./RefMark";

/**
 * The placeholders of the custom field `id`.
 */
export type KeyValueReferences = { id: string, marks: Array<RefMark>, };
