// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A custom field in the detail view: its name and its stored value with the placeholders as they
 * are. Custom values show unmasked in the window (amends spec 034 FR-005); a placeholder's
 * resolved value still comes only through `passwords_reveal`.
 */
export type KeyValueView = { id: string, key: string | null, value: string | null, hasValue: boolean, };
