// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestOutcome } from "./TestOutcome";

/**
 * The last test of a storage on this device.
 */
export type LastTest = { at: string, outcome: TestOutcome, };
