// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncServers } from "./SyncServers";

export type LinkJoinStartArgs = { code: string, vaultName: string, deviceName: string, passphrase: string, 
/**
 * The servers the vault's devices find each other through, when they are
 * not the built-in ones; omitted `servers` means the built-in ones, while
 * explicit `disabled` entries can switch any listed server off.
 */
servers?: SyncServers, };
