// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a join failed.
 */
export type LinkFailure = "expired" | "used" | "wrong_code" | "rejected" | "incompatible" | "connection_lost";
