// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkFailure } from "./LinkFailure";

/**
 * The join on the new installation.
 */
export type LinkJoinState = { "state": "searching" } | { "state": "waiting_for_confirmation" } | { "state": "transferring", progress: number, } | { "state": "done", vaultName: string, } | { "state": "failed", reason: LinkFailure, };
