// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkConfirmArgs = { 
/**
 * Whether the new device also becomes a main device.
 */
asMainDevice: boolean, };
