// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The code a main device shows.
 */
export type LinkCodeInfo = { code: string, qrSvg: string, 
/**
 * Milliseconds since the epoch.
 */
expiresAt: number, };
