// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkingStage } from "./LinkingStage";

/**
 * The link in progress on a main device, `null` when there is none.
 */
export type LinkingStatus = { stage: LinkingStage, newDeviceName?: string, };
