// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The entry a linked passkey belongs to (spec 036, research R6).
 */
export type LinkedFrom = { itemId: string, title: string | null, };
