// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkJoinStartArgs = { code: string, vaultName: string, deviceName: string, passphrase: string, };
