// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a link stands on the main device.
 */
export type LinkingStage = "code_shown" | "awaiting_confirmation";
