// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry as the settings and the extension read it.
 */
export type LogEntry = { id: number, 
/**
 * `debug`, `info`, `warn` or `error`.
 */
level: string, message: string, 
/**
 * The JSON the extension gave, as text.
 */
metadata?: string, 
/**
 * Milliseconds.
 */
createdAt: number, };
