// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which presets of the model catalogs this device gets (spec 043 FR-027, FR-030, research R11).
 */
export type ModelPresets = "desktop" | "phone";
