// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Target } from "./Target";

export type MoveArgs = { targets: Array<Target>, 
/**
 * The folder to move into; `null` is the top level.
 */
toGroupId: string | null, };
