// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to do with an entry the vault already has (FR-023).
 */
export type OnDuplicate = "skip" | "create";
