// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One open request to join the vault (FR-045).
 */
export type OpenAdmission = { devicePubkey: string, name: string, requestedAt: number, };
