// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./Entry";
import type { ViewerKind } from "./ViewerKind";

/**
 * What the viewer gets for a file (contracts/tauri-commands.md, `files_open`).
 */
export type Opened = { kind: ViewerKind,
/**
 * The media server's URL for image, video, audio and PDF; released with the tab.
 */
url: string | null, entry: Entry, };
