// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the stored TOTP secret can produce a code. A value that arrived through sync or an
 * import can be invalid (FR-003); the entry then shows a message instead of a code.
 */
export type OtpState = "none" | "valid" | "invalid";
