// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupRow } from "./GroupRow";
import type { ItemHeader } from "./ItemHeader";
import type { TagRow } from "./TagRow";

/**
 * Everything the window needs for its store in one answer: every entry (also those in the trash,
 * the window separates them), every folder, every tag with its count. The user's overview only;
 * callers from outside get `list_headers`.
 */
export type Overview = { headers: Array<ItemHeader>, groups: Array<GroupRow>, tags: Array<TagRow>, };
