// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PasskeyRenameArgs = { passkeyId: string, 
/**
 * `None` clears the nickname.
 */
nickname: string | null, };
