// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PasskeyUnlinkArgs = {
/**
 * The entry that shows the passkey of another entry.
 */
itemId: string, passkeyId: string, };
