// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A passkey of an entry without its keys (FR-004).
 */
export type PasskeyView = { id: string, relyingPartyId: string, relyingPartyName: string | null, userName: string | null, nickname: string | null, algorithm: number, createdAt: string | null, lastUsedAt: string | null, };
