// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One permission as the settings show it.
 */
export type PermissionView = {
/**
 * Row id; `None` for a decision held in memory.
 */
id?: string, kind: string, action: string, target: string,
/**
 * `granted`, `denied` or `ask`.
 */
status: string, declared: boolean,
/**
 * Holds on every own device.
 */
allDevices: boolean,
/**
 * The device a device-scoped row holds on.
 */
deviceName?: string,
/**
 * Held only until holzi is closed.
 */
temporary: boolean,
/**
 * holzi cannot read the row (FR-022); it counts as absent.
 */
unreadable: boolean, };
