// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionSetArgs = { extensionId: string, kind: string, action: string, target: string,
/**
 * `granted`, `denied` or `ask`.
 */
status: string,
/**
 * The row this setting replaces, if any: a row of a scope the kind no longer has.
 */
replaces: string | null, };
