// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionDecision } from "./PermissionDecision";

export type PermissionResolveArgs = { requestId: string, decision: PermissionDecision, 
/**
 * Store the decision; else it holds until holzi is closed.
 */
remember: boolean, 
/**
 * For device-scoped kinds: remember for every own device.
 */
allDevices: boolean, };
