// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionSetArgs = { extensionId: string, kind: string, action: string, target: string,
/**
 * `granted`, `denied` or `ask`.
 */
status: string,
/**
 * The row whose state this setting changes, if any. It keeps its scope when the scope fits
 * its kind (a shell row of another device stays on that device); a row from before
 * Clarifications 2026-10-06 whose scope no longer fits is replaced by one in the kind's scope.
 */
replaces: string | null, };
