// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionSetArgs = { extensionId: string, kind: string, action: string, target: string, 
/**
 * `granted`, `denied` or `ask`.
 */
status: string, 
/**
 * Remember for every own device; else for this device only.
 */
allDevices: boolean, 
/**
 * The row this setting replaces (a change of scope), if any.
 */
replaces: string | null, };
