// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionRemoveArgs = { extensionId: string,
/**
 * A remembered row.
 */
permissionId: string | null,
/**
 * A decision held in memory: `kind|action|target`.
 */
temporaryKey: string | null, };
