// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The answer of holzi's window (`extension_permission_resolve`).
 */
export type PermissionDecision = "allow" | "deny";
