// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's choice for one declared permission.
 */
export type PermissionChoice = { kind: string, action: string, target: string, 
/**
 * Ticked: `granted`; unticked: `ask`.
 */
granted: boolean, };
