// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One open question, as holzi's window shows it.
 */
export type PermissionRequestEvent = { requestId: string, extensionId: string, displayName: string, kind: string, action: string, target: string, 
/**
 * The manifest declares this permission.
 */
declared: boolean, 
/**
 * Remembered for this device only unless "for all devices" is chosen.
 */
deviceScoped: boolean, 
/**
 * A `database` target of an extension that is not installed: only "Verweigern" is offered.
 */
targetMissing: boolean, };
