// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The phase a progress event reports.
 */
export type Phase = "groups" | "items" | "attachments" | "rollback";
