// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `open` and `save` of `@tauri-apps/plugin-dialog` return, passed on unchanged (a newtype,
 * so it travels as the bare string).
 */
export type PickedFile = string;
