// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlatformName } from "./PlatformName";

/**
 * The facilities of this device; fixed for the life of the process.
 */
export type PlatformCapabilities = { platform: PlatformName, 
/**
 * The CLI delegates (claude, codex): external programs with a terminal.
 */
cliDelegates: boolean, 
/**
 * The chat tool `run_command`.
 */
commandTool: boolean, 
/**
 * The terminal of extensions.
 */
terminal: boolean, 
/**
 * Watching folders for extensions.
 */
folderWatch: boolean, 
/**
 * File paths outside a dialog choice for extensions.
 */
freePaths: boolean, 
/**
 * Choosing a folder in a dialog.
 */
folderPick: boolean, 
/**
 * Detecting a graphics card for model recommendations.
 */
gpuDetection: boolean, 
/**
 * Closing the vault restarts the app at the vault picker (spec 013); otherwise it ends.
 */
relaunchOnClose: boolean, 
/**
 * The screen capture protection setting exists (FR-011a).
 */
screenCapture: boolean, 
/**
 * The system has a back gesture (spec 020 FR-019).
 */
backGesture: boolean, };
