// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The platform holzi runs on.
 */
export type PlatformName = "linux" | "macos" | "windows" | "android" | "ios";
