// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved generator configuration (FR-014). Exactly one preset is the default; with two flagged
 * ones (concurrent writes on two devices) the list shows only the newest as the default.
 */
export type Preset = { id: string, name: string, length: number, uppercase: boolean, lowercase: boolean, numbers: boolean, symbols: boolean, excludeChars: string, usePattern: boolean, pattern: string, isDefault: boolean, };
