// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the window sends to save a preset; an empty `id` creates one.
 */
export type PresetInput = { id: string, name: string, length: number, uppercase: boolean, lowercase: boolean, numbers: boolean, symbols: boolean, excludeChars: string, usePattern: boolean, pattern: string, isDefault: boolean, };
