// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";

/**
 * The payload of `passwords-import-progress`.
 */
export type Progress = { done: number, total: number, phase: Phase, };
