// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The provider a connection was created for; it only prefills endpoint and addressing.
 */
export type ProviderKind = "aws" | "rustfs" | "other";
