// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many other entries point at an entry (FR-048), before it is deleted for good.
 */
export type ReferenceUsage = { itemId: string, 
/**
 * Entries with a placeholder on this one in a text field.
 */
targetItems: number, 
/**
 * Entries that use one of its passkeys through a link (stage 4).
 */
passkeyLinks: number, };
