// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefMarkKind } from "./RefMarkKind";

export type ReferenceTokenArgs = { itemId: string, kind: RefMarkKind, key?: string, };
