// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The value a placeholder points at.
 */
export type RefMarkKind = "username" | "password" | "extra";
