// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a placeholder resolves for the user.
 */
export type RefStatus = "ok" | "missing" | "cycle" | "tooDeep";
