// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a removal takes with it (FR-007): the storages and the extensions that lose access.
 */
export type RemovalPreview = { storages: Array<string>, extensions: Array<string>, };
