// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `storage_removal_preview`: one of the two ids.
 */
export type RemovalTarget = { connectionId?: string, storageId?: string, };
