// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReorderGroupsArgs = {
/**
 * The folder whose children are reordered; `null` is the top level.
 */
parentId: string | null,
/**
 * All siblings of that level, in the new order.
 */
orderedIds: Array<string>, };
