// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportReport } from "./ImportReport";

export type ReportSaveArgs = { report: ImportReport,
/**
 * A path from the save dialog.
 */
path: string, };
