// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a restore of a history state did.
 */
export type RestoreOutcome = { updatedAt: string,
/**
 * File names of attachments whose binary data is gone and that were therefore not re-linked.
 */
skippedAttachments: Array<string>, };
