// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A secret on its way to the user's eyes: the one type that serialises a value to the webview.
 * Zeroed when dropped; `Debug` prints no value.
 */
export type RevealedSecret = { value: string, };
