// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretField } from "./SecretField";

export type RevealArgs = { itemId: string, field: SecretField, };
