// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileCategory } from "./FileCategory";

/**
 * What a search keeps to (FR-029). Size and type only let files through.
 */
export type SearchFilters = { types?: Array<FileCategory>, sizeMin?: number, sizeMax?: number,
/**
 * Milliseconds since 1970.
 */
modifiedFrom?: number, modifiedTo?: number, };
