// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./Entry";

/**
 * One hit.
 */
export type SearchHit = { entry: Entry,
/**
 * Higher is better.
 */
score: number, };
