// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which secret of an entry to reveal.
 */
export type SecretField = { "kind": "password" } | { "kind": "otpSecret" } | { "kind": "keyValue", id: string, } | { "kind": "username" } | { "kind": "url" } | { "kind": "note" };
