// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Device value, vault value and the value that applies on this device.
 */
export type SessionRestoreState = { device: boolean | null, vault: boolean | null, effective: boolean, };
