// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the session is saved and restored, for every device of the vault.
 */
export type SessionRestoreState = { enabled: boolean, };
