// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRestoreScope } from "./SessionRestoreScope";

export type SessionRestoreSetArgs = { scope: SessionRestoreScope, 
/**
 * `null` resets the value in `scope`.
 */
enabled: boolean | null, };
