// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowDto } from "./WindowDto";
import type { WorkspaceDto } from "./WorkspaceDto";

export type ShellLayoutDto = { workspaces: Array<WorkspaceDto>, windows: Array<WindowDto>, activeWorkspaceId: string, };
