// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An attachment of a history state.
 */
export type SnapshotAttachmentView = { fileName: string, binaryHash: string, 
/**
 * Whether the binary data is still there (a restore skips the attachment if it is not).
 */
available: boolean, };
