// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotAttachmentView } from "./SnapshotAttachmentView";
import type { SnapshotKeyValueView } from "./SnapshotKeyValueView";

/**
 * One history state of an entry without its secrets (FR-017): flags instead of the password, the
 * TOTP secret and the values of custom fields; the values come only through `history_reveal`.
 */
export type SnapshotView = { id: string, itemId: string, modifiedAt: string | null, title: string | null, username: string | null, url: string | null, note: string | null, icon: string | null, color: string | null, expiresAt: string | null, hasPassword: boolean, hasOtpSecret: boolean, otpDigits: number | null, otpPeriod: number | null, otpAlgorithm: string | null, tags: Array<string>, keyValues: Array<SnapshotKeyValueView>, attachments: Array<SnapshotAttachmentView>, };
