// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key-value of a history state in the masked view: the name, whether it has a value.
 */
export type SnapshotKeyValueView = { key: string | null, hasValue: boolean, };
