// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One state in the history of an entry, with the names of the fields that changed against the
 * state before it (values of secret fields only through `history_reveal`).
 */
export type SnapshotHeader = { id: string, itemId: string, modifiedAt: string | null, changedFields: Array<string>, attachmentCount: number, };
