// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the file browser looks (spec 044 FR-002): the device, or a storage of spec 038.
 */
export type SourceRef = { "kind": "device" } | { "kind": "storage", storageId: string, };
