// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Drive } from "./Drive";
import type { KnownPlace } from "./KnownPlace";

/**
 * What the sidebar shows.
 */
export type Sources = { drives: Array<Drive>, known: Array<KnownPlace>, };
