// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A storage for the sidebar.
 */
export type StorageSource = { id: string, name: string, };
