// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestOutcome } from "./TestOutcome";

/**
 * What holzi's window learns of the credentials it sent (`storage_dialog_resolve`).
 */
export type StorageTrial = { "kind": "ended" } | { "kind": "failed", outcome: TestOutcome,
/**
 * The test object holzi could not delete, if the failed probe left one behind.
 */
leftoverKey: string | null, };
