// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastTest } from "./LastTest";

/**
 * A storage as the settings show it.
 */
export type StorageView = { id: string, connectionId: string, name: string, bucket: string, lastTest: LastTest | null,
/**
 * The extensions with a permission for this storage.
 */
extensions: Array<string>, };
