// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionView } from "./ConnectionView";
import type { StorageView } from "./StorageView";

/**
 * `storage_list`.
 */
export type StorageOverview = { connections: Array<ConnectionView>, storages: Array<StorageView>, };
