// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialsInput } from "./CredentialsInput";

/**
 * The user's answer to a storage dialog (contracts/tauri-commands.md `storage_dialog_resolve`).
 */
export type StorageAnswer = { "kind": "cancel" } | { "kind": "confirm",
/**
 * An existing connection the user chose for the new storage.
 */
connectionId?: string,
/**
 * New credentials; only holzi's window over the whole app sends them.
 */
credentials?: CredentialsInput, name?: string, bucket?: string, };
