// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `storage_save`: a new storage without `id`, otherwise a change of one.
 */
export type StorageInput = { id?: string, connectionId: string, name: string, bucket: string, };
