// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkingStatus } from "./LinkingStatus";
import type { OpenAdmission } from "./OpenAdmission";
import type { ThisDevice } from "./ThisDevice";

/**
 * What the device list view needs besides the devices.
 */
export type SyncStatus = { thisDevice: ThisDevice, openAdmissions: Array<OpenAdmission>, linking: LinkingStatus | null,
/**
 * This vault file is the copy of a main device and this device enrolled
 * itself as a main device; the user has not read that yet (FR-044).
 */
copyEnrolledAsMain: boolean, };
