// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The servers devices find each other through (FR-008).
 */
export type SyncServers = { nostrRelays: Array<string>, irohRelays: Array<string>, };
