// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkingStatus } from "./LinkingStatus";
import type { OpenAdmission } from "./OpenAdmission";
import type { ThisDevice } from "./ThisDevice";

/**
 * What the device list view needs besides the devices.
 */
export type SyncStatus = { thisDevice: ThisDevice, openAdmissions: Array<OpenAdmission>, linking: LinkingStatus | null, };
