// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tag as the lists show it.
 */
export type TagRef = { id: string, name: string, color: string | null, };
