// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetKind } from "./TargetKind";

/**
 * An entry or a folder, named by its id.
 */
export type Target = { kind: TargetKind, id: string, };
