// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestOutcome } from "./TestOutcome";

/**
 * `storage_test`: the outcome, and the key of a test object holzi could not delete (SC-004).
 */
export type TestResult = { outcome: TestOutcome, leftoverKey: string | null, };
