// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a connection test (research R9), stored per device in `storage_tests_no_sync`.
 */
export type TestOutcome = "passed" | "accessDenied" | "unreachable" | "bucketMissing" | "missingRight";
