// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The field a text copied from the window comes from (`passwords_copy_text`): its placeholders
 * are resolved as in that field of the entry (spec 036, FR-045).
 */
export type TextField = { "kind": "username" } | { "kind": "password" } | { "kind": "url" } | { "kind": "note" } | { "kind": "keyValue", key: string, };
