// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A text for the viewer.
 */
export type TextContent = { text: string,
/**
 * The file is longer than [`TEXT_LIMIT`]; only its start is in `text`.
 */
truncated: boolean, };
