// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What this device is in the vault (spec 024, FR-034).
 */
export type ThisDevice = "main" | "linked" | "awaiting_admission" | "removed";
