// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The current TOTP code of an entry, computed in Rust (FR-003).
 */
export type TotpCode = { code: string, remainingSeconds: number, period: number, digits: number, };
