// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceRef } from "./SourceRef";

/**
 * Where a copy or move goes.
 */
export type TransferTarget = { source: SourceRef, path: string, };
