// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far a transfer is.
 */
export type TransferProgress = { itemsDone: number, itemsTotal: number, bytesDone: number, bytesTotal: number, };
