// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilesError } from "./FilesError";
import type { TransferProgress } from "./TransferProgress";

/**
 * What the window hears of a transfer.
 */
export type TransferEvent = { "kind": "progress", progress: TransferProgress, } | { "kind": "conflict", name: string, } | { "kind": "done" } | { "kind": "cancelled" } | { "kind": "failed", error: FilesError, };
