// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemPatch } from "./ItemPatch";

export type UpdateItemArgs = { itemId: string, 
/**
 * The `updatedAt` the window read; a newer one on disk is a conflict.
 */
expectedUpdatedAt: string, patch: ItemPatch, };
