// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The public key of the vault identity (FR-046).
 */
export type VaultPublicIdentity = { 
/**
 * Nostr `npub` form, the address others invite the vault at.
 */
npub: string, hex: string, };
