// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceProblem } from "./DeviceProblem";
import type { DeviceRole } from "./DeviceRole";

/**
 * One device of the vault for the settings' device list.
 */
export type VaultDevice = { vaultDeviceUuid: string,
/**
 * The device key as hex.
 */
devicePubkey: string,
/**
 * `None` for a device that has no name yet.
 */
alias: string | null, role: DeviceRole, isCurrent: boolean,
/**
 * Whether a session with it is open right now.
 */
online: boolean,
/**
 * Milliseconds since the epoch; `None` when this device knows of no time.
 */
lastSeen: number | null, problem: DeviceProblem | null, };
