// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the viewer shows a file.
 */
export type ViewerKind = "text" | "pdf" | "image" | "video" | "audio" | "info";
