// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabDto } from "./TabDto";

export type WindowDto = { windowId: string, workspaceId: string, x: number, y: number, width: number, height: number, isMinimized: boolean, isMaximized: boolean, stackOrder: number, activeTabId: string, tabs: Array<TabDto>, };
