// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRestoreState } from "./SessionRestoreState";

export type WmSessionLoad = { restore: SessionRestoreState, 
/**
 * The saved session as the frontend wrote it, validated there.
 */
session: unknown, };
