//! A haex-vault vault built at run time (spec 037, T006): an SQLCipher file opened the way
//! haex-vault opens it (`PRAGMA key` with the vault password, SQLCipher defaults, WAL), with the
//! password manager tables of `tests/fixtures/passwords/haex_vault_0000_passwords.sql`, the three
//! columns its sync layer adds at run time, and rows that cover every line of
//! `specs/037-haex-vault-import/contracts/haex-vault-mapping.md`. Nothing of it is stored in the
//! repository; the passkey pair is generated by the test (constitution I).
//! Included per binary next to `kdbx_fixture` (its `passkey` makes the key pair).
#![allow(dead_code)]

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use base64::engine::general_purpose::STANDARD;
use base64::Engine;
use haex_crdt::rusqlite::{params, Connection};
use sha2::{Digest, Sha256};

use super::kdbx_fixture::{passkey, TestPasskey};

pub const PASSWORD: &str = "haex-vault-fixture";
/// Planted in the secrets of the fixture; no report, error or text may carry it.
pub const MARKER: &str = "SECRET-MARKER-HAEX-VAULT";
pub const ATTACHMENT: &[u8] = b"attachment bytes of the haex-vault fixture";
pub const HISTORY_ATTACHMENT: &[u8] = b"an attachment of an earlier state";
pub const ICON: &[u8] = b"\x89PNG picture of the haex-vault fixture";
/// The title of the entry that only the `-wal` file holds (see [`build_with_wal`]).
pub const WAL_TITLE: &str = "Only in the WAL";

const SCHEMA: &str = include_str!("../fixtures/passwords/haex_vault_0000_passwords.sql");
const CRDT_COLUMNS: [&str; 3] = [
    "haex_hlc TEXT",
    "haex_column_hlcs TEXT NOT NULL DEFAULT '{}'",
    "haex_column_sigs TEXT NOT NULL DEFAULT '{}'",
];

pub struct HaexVault {
    pub path: PathBuf,
    /// The pair of the passkey on the full entry.
    pub passkey: TestPasskey,
}

pub fn sha256_hex(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

/// Opens (or creates) a haex-vault file the way haex-vault does.
pub fn open(path: &Path) -> Connection {
    let conn = Connection::open(path).expect("open the haex-vault file");
    conn.pragma_update(None, "key", PASSWORD).expect("key");
    // The rows include broken references on purpose (a missing parent, a cycle), as the sync of
    // haex-vault can leave them; it applies remote rows without foreign keys.
    conn.pragma_update(None, "foreign_keys", "OFF")
        .expect("foreign keys");
    let mode: String = conn
        .query_row("PRAGMA journal_mode = WAL", [], |r| r.get(0))
        .expect("wal");
    assert_eq!(mode, "wal");
    conn
}

/// Creates the password manager tables as haex-vault has them at run time.
pub fn create_schema(conn: &Connection) {
    conn.execute_batch(SCHEMA).expect("schema");
    let tables: Vec<String> = conn
        .prepare("SELECT name FROM sqlite_master WHERE type = 'table'")
        .expect("tables")
        .query_map([], |r| r.get(0))
        .expect("tables")
        .collect::<Result<_, _>>()
        .expect("tables");
    for table in tables {
        for column in CRDT_COLUMNS {
            conn.execute_batch(&format!("ALTER TABLE {table} ADD COLUMN {column}"))
                .expect("crdt column");
        }
    }
}

fn binary(conn: &Connection, bytes: &[u8], kind: &str) -> String {
    let hash = sha256_hex(bytes);
    conn.execute(
        "INSERT INTO haex_passwords_binaries (hash, data, size, type) VALUES (?1, ?2, ?3, ?4)",
        params![hash, STANDARD.encode(bytes), bytes.len() as i64, kind],
    )
    .expect("binary");
    hash
}

fn group(conn: &Connection, id: &str, name: &str, parent: Option<&str>) {
    conn.execute(
        "INSERT INTO haex_passwords_groups (id, name, parent_id) VALUES (?1, ?2, ?3)",
        params![id, name, parent],
    )
    .expect("group");
}

fn item(conn: &Connection, id: &str, title: &str, icon: Option<&str>, group: Option<&str>) {
    conn.execute(
        "INSERT INTO haex_passwords_item_details (id, title, password, icon) \
         VALUES (?1, ?2, ?3, ?4)",
        params![id, title, format!("{MARKER}-{id}"), icon],
    )
    .expect("item");
    if let Some(group) = group {
        conn.execute(
            "INSERT INTO haex_passwords_group_items (item_id, group_id) VALUES (?1, ?2)",
            params![id, group],
        )
        .expect("group item");
    }
}

fn snapshot(conn: &Connection, id: &str, data: &str, created: &str, modified: Option<&str>) {
    conn.execute(
        "INSERT INTO haex_passwords_item_snapshots \
         (id, item_id, snapshot_data, created_at, modified_at) VALUES (?1, 'i-full', ?2, ?3, ?4)",
        params![id, data, created, modified],
    )
    .expect("snapshot");
}

/// Writes every row of the mapping contract.
fn fill(conn: &Connection) -> TestPasskey {
    let icon = binary(conn, ICON, "icon");
    let attachment = binary(conn, ATTACHMENT, "attachment");
    let history = binary(conn, HISTORY_ATTACHMENT, "attachment");
    conn.execute(
        "INSERT INTO haex_passwords_binaries (hash, data, size, type) \
         VALUES ('broken', '!!! not base64 !!!', 3, 'attachment')",
        [],
    )
    .expect("broken binary");

    // Folders: three levels with every column, the trash with a folder below it, a cycle and a
    // folder whose parent does not exist.
    conn.execute(
        "INSERT INTO haex_passwords_groups (id, name, description, icon, sort_order, color) \
         VALUES ('g-work', 'Work', 'Work stuff', 'mdi:briefcase', 2, '#ff0000')",
        [],
    )
    .expect("group");
    conn.execute(
        "INSERT INTO haex_passwords_groups (id, name, icon, sort_order, parent_id) \
         VALUES ('g-mail', 'Mail', 'i-lucide-mail', 1, 'g-work')",
        [],
    )
    .expect("group");
    group(conn, "g-deep", "Deep", Some("g-mail"));
    conn.execute(
        "INSERT INTO haex_passwords_groups (id, name, icon) \
         VALUES ('trash', 'Papierkorb', 'i-lucide-trash-2')",
        [],
    )
    .expect("trash");
    group(conn, "g-old", "Old", Some("trash"));
    group(conn, "g-cycle-a", "Cycle A", Some("g-cycle-b"));
    group(conn, "g-cycle-b", "Cycle B", Some("g-cycle-a"));
    group(conn, "g-orphan", "Orphan", Some("missing-parent"));

    // The full entry.
    conn.execute(
        "INSERT INTO haex_passwords_item_details \
         (id, title, username, password, note, icon, color, url, otp_secret, otp_digits, \
          otp_period, otp_algorithm, expires_at, autofill_aliases, created_at, updated_at) \
         VALUES ('i-full', 'Full Entry', 'alice', ?1, 'a note', ?2, '#00ff00', \
                 'https://example.invalid', 'JBSWY3DPEHPK3PXP', 8, 60, 'SHA256', '2027-01-31', \
                 '{\"username\":[\"email\",\"login\"]}', '2024-01-02 03:04:05', \
                 '2024-02-03T04:05:06.789Z')",
        params![format!("{MARKER}-full"), format!("binary:{icon}")],
    )
    .expect("full item");
    conn.execute(
        "INSERT INTO haex_passwords_group_items (item_id, group_id) VALUES ('i-full', 'g-deep')",
        [],
    )
    .expect("group item");
    // Custom fields: ids out of order, so only rowid gives the order of the editor.
    for (id, key, value) in [
        ("kv-z", "first", "1"),
        ("kv-a", "second", "2"),
        ("kv-m", "third", "3"),
    ] {
        conn.execute(
            "INSERT INTO haex_passwords_item_key_values (id, item_id, key, value) \
             VALUES (?1, 'i-full', ?2, ?3)",
            params![id, key, value],
        )
        .expect("key value");
    }
    conn.execute(
        "INSERT INTO haex_passwords_item_binaries (id, item_id, binary_hash, file_name) \
         VALUES ('ib-1', 'i-full', ?1, 'file.txt')",
        params![attachment],
    )
    .expect("attachment");

    // Tags: a coloured one, a plain one and a case variant of the first.
    conn.execute(
        "INSERT INTO haex_passwords_tags (id, name, color) VALUES \
         ('t-work', 'Work', '#123456'), ('t-private', 'Private', NULL), ('t-work-lower', 'work', NULL)",
        [],
    )
    .expect("tags");
    conn.execute(
        "INSERT INTO haex_passwords_item_tags (id, item_id, tag_id) VALUES \
         ('it-1', 'i-full', 't-work'), ('it-2', 'i-full', 't-private'), \
         ('it-3', 'i-null-otp', 't-work-lower')",
        [],
    )
    .expect("item tags");

    // History in the three forms haex-vault writes, and one that cannot be read.
    snapshot(
        conn,
        "s-editor",
        r#"{"title":"Full v1","username":"alice","password":"old","url":null,"note":null,"icon":"i-lucide-key","color":null,"expiresAt":null,"otpSecret":null,"tagNames":["Work"],"keyValues":[{"key":"k","value":"v"}],"attachments":[]}"#,
        "2023-01-01 00:00:00",
        Some("2023-01-01T00:00:00.000Z"),
    );
    snapshot(
        conn,
        "s-keepass",
        r#"{"title":"Full v2","username":"alice","password":"older","url":null,"note":null,"icon":null,"color":null,"expiresAt":null,"otpSecret":null,"tagNames":[],"keyValues":[],"attachments":[]}"#,
        "2023-02-01T00:00:00.000Z",
        None,
    );
    conn.execute(
        "INSERT INTO haex_passwords_snapshot_binaries (id, snapshot_id, binary_hash, file_name) \
         VALUES ('sb-1', 's-keepass', ?1, 'old.txt')",
        params![history],
    )
    .expect("snapshot binary");
    snapshot(
        conn,
        "s-external",
        r#"{"title":"Full v3","username":"alice","password":"p3","url":null,"note":null,"tags":null,"otpSecret":null,"otpDigits":6,"otpPeriod":30,"otpAlgorithm":"SHA1","icon":null,"keyValues":[],"attachments":[]}"#,
        "2023-03-01T00:00:00.000Z",
        Some("2023-03-01T00:00:00.000Z"),
    );
    snapshot(
        conn,
        "s-broken",
        "{not json",
        "2023-04-01T00:00:00.000Z",
        None,
    );

    // The other entries, each for one rule.
    conn.execute(
        "INSERT INTO haex_passwords_item_details \
         (id, title, password, icon, otp_secret, otp_digits, otp_period, otp_algorithm) \
         VALUES ('i-null-otp', 'Null OTP', ?1, 'mdi:bank', 'not base32 !!', NULL, NULL, NULL)",
        params![format!("{MARKER}-null-otp")],
    )
    .expect("null otp item");
    item(conn, "i-trash", "Trashed", None, Some("trash"));
    item(conn, "i-old", "In an old folder", None, Some("g-old"));
    item(
        conn,
        "i-unknown-icon",
        "Unknown icon",
        Some("something-weird"),
        Some("g-orphan"),
    );
    item(
        conn,
        "i-missing-icon",
        "Missing picture",
        Some("binary:0000"),
        Some("g-cycle-a"),
    );
    item(conn, "i-lucide", "Lucide icon", Some("i-lucide-key"), None);
    item(conn, "i-broken", "Broken attachment", None, None);
    conn.execute(
        "INSERT INTO haex_passwords_item_binaries (id, item_id, binary_hash, file_name) \
         VALUES ('ib-2', 'i-broken', 'broken', 'broken.bin')",
        [],
    )
    .expect("broken attachment");

    // Passkeys: one on the full entry, one without an entry.
    let pair = passkey(-7);
    conn.execute(
        "INSERT INTO haex_passwords_passkeys \
         (id, item_id, credential_id, relying_party_id, relying_party_name, user_handle, user_name, \
          user_display_name, private_key, public_key, algorithm, sign_count, is_discoverable, \
          nickname, created_at, last_used_at) \
         VALUES ('pk-1', 'i-full', 'Y3JlZC1mdWxs', 'example.invalid', 'Example', 'dXNlcg==', 'alice', \
                 'Alice', ?1, ?2, -7, 5, 1, 'Laptop', '2024-05-01 10:00:00', \
                 '2024-06-01T10:00:00.000Z')",
        params![pair.private_b64, pair.public_b64],
    )
    .expect("passkey");
    conn.execute(
        "INSERT INTO haex_passwords_passkeys \
         (id, item_id, credential_id, relying_party_id, user_handle, private_key, public_key, \
          algorithm, sign_count, is_discoverable) \
         VALUES ('pk-2', NULL, 'c3RhbmRhbG9uZQ==', 'standalone.invalid', 'b3RoZXI=', ?1, ?2, -7, 0, 0)",
        params![pair.private_b64, pair.public_b64],
    )
    .expect("standalone passkey");

    // Generator presets, one of them the default.
    conn.execute(
        "INSERT INTO haex_passwords_generator_presets \
         (id, name, length, uppercase, lowercase, numbers, symbols, exclude_chars, use_pattern, \
          pattern, is_default) VALUES \
         ('p-strong', 'Strong', 32, 1, 1, 1, 1, '', 0, '', 1), \
         ('p-pin', 'PIN', 6, 0, 0, 1, 0, '0', 0, '', 0)",
        [],
    )
    .expect("presets");
    pair
}

/// A closed haex-vault file in `dir` holding every row of the contract (no `-wal` left).
pub fn build(dir: &Path) -> HaexVault {
    let path = dir.join("vault.db");
    let conn = open(&path);
    create_schema(&conn);
    let passkey = fill(&conn);
    drop(conn);
    HaexVault { path, passkey }
}

/// Like [`build`], then one more entry written through a connection that stays open with
/// checkpoints off, so that entry is only in `vault.db-wal`. Keep the connection alive while the
/// import reads the file.
pub fn build_with_wal(dir: &Path) -> (HaexVault, Connection) {
    let vault = build(dir);
    let conn = open(&vault.path);
    conn.pragma_update(None, "wal_autocheckpoint", 0)
        .expect("no checkpoints");
    item(&conn, "i-wal", WAL_TITLE, None, None);
    (vault, conn)
}

/// The SHA-256 of every file in the directory of `path`, by name, to prove the source untouched.
pub fn sha256_files(path: &Path) -> BTreeMap<String, String> {
    let dir = path.parent().expect("parent");
    std::fs::read_dir(dir)
        .expect("read dir")
        .map(|entry| {
            let entry = entry.expect("entry");
            let bytes = std::fs::read(entry.path()).expect("read");
            (
                entry.file_name().to_string_lossy().into_owned(),
                sha256_hex(&bytes),
            )
        })
        .collect()
}
